---
name: "tagged-release"

on:
  push:
    tags:
      - "v0.2.*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "windows-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.jar
